FiveGuard = "fg" -- your fiveguard resource name

Config = {
    ["wlasciciel"] = { -- esx group name
        ["Client"] = { -- category name
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
        ["Weapon"] = {
            "BypassWeaponDmgModifier",
            "BypassInfAmmo",
            "BypassNoReload",
            "BypassRapidFire",
        },
        ["Vehicle"] = {
            "BypassVehicleFixAndGodMode",
            "BypassVehicleHandlingEdit",
            "BypassVehicleModifier",
            "BypassBulletproofTires",
        },
        ["Blacklist"] = {
            "BypassModelChanger",
            "BypassWeaponBlacklist"
        },
        ["Misc"] = {
            "FGCommands",
            "BypassVPN",
            "BypassExplosion",
            "BypassClearTasks",
            "BypassParticle",
        },
    },
    
    ["wspolwlasciciel"] = { -- esx group name
        ["Client"] = { -- category name
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
        ["Weapon"] = {
            "BypassWeaponDmgModifier",
            "BypassInfAmmo",
            "BypassNoReload",
            "BypassRapidFire",
        },
        ["Vehicle"] = {
            "BypassVehicleFixAndGodMode",
            "BypassVehicleHandlingEdit",
            "BypassVehicleModifier",
            "BypassBulletproofTires",
        },
        ["Blacklist"] = {
            "BypassModelChanger",
            "BypassWeaponBlacklist"
        },
        ["Misc"] = {
            "FGCommands",
            "BypassVPN",
            "BypassExplosion",
            "BypassClearTasks",
            "BypassParticle",
        },
    },

    ["admin"] = { -- esx group name
        ["Client"] = { -- category name
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
        ["Weapon"] = {
            "BypassWeaponDmgModifier",
            "BypassInfAmmo",
            "BypassNoReload",
            "BypassRapidFire",
        },
        ["Vehicle"] = {
            "BypassVehicleFixAndGodMode",
            "BypassVehicleHandlingEdit",
            "BypassVehicleModifier",
            "BypassBulletproofTires",
        },
        ["Blacklist"] = {
            "BypassModelChanger",
            "BypassWeaponBlacklist"
        },
        ["Misc"] = {
            "FGCommands",
            "BypassVPN",
            "BypassExplosion",
            "BypassClearTasks",
            "BypassParticle",
        },
    },

    ["superadmin"] = { -- esx group name
        ["Client"] = { -- category name
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
        ["Weapon"] = {
            "BypassWeaponDmgModifier",
            "BypassInfAmmo",
            "BypassNoReload",
            "BypassRapidFire",
        },
        ["Vehicle"] = {
            "BypassVehicleFixAndGodMode",
            "BypassVehicleHandlingEdit",
            "BypassVehicleModifier",
            "BypassBulletproofTires",
        },
        ["Blacklist"] = {
            "BypassModelChanger",
            "BypassWeaponBlacklist"
        },
        ["Misc"] = {
            "FGCommands",
            "BypassVPN",
            "BypassExplosion",
            "BypassClearTasks",
            "BypassParticle",
        },
    },

    ["admin"] = { -- esx group name
    ["Client"] = { -- category name
        "BypassSpectate",
        "BypassGodMode",
        "BypassInvisible",
        "BypassStealOutfit",
        "BypassInfStamina",
        "BypassNoclip",
        "BypassSuperJump",
        "BypassFreecam",
        "BypassSpeedHack",
        "BypassTeleport",
        "BypassNightVision",
        "BypassThermalVision",
        "BypassOCR",
        "BypassNuiDevtools",
        "BypassBlacklistedTextures",
        "BlipsBypass",
        "BypassCbScanner",
    },
    ["Weapon"] = {
        "BypassWeaponDmgModifier",
        "BypassInfAmmo",
        "BypassNoReload",
        "BypassRapidFire",
    },
    ["Vehicle"] = {
        "BypassVehicleFixAndGodMode",
        "BypassVehicleHandlingEdit",
        "BypassVehicleModifier",
        "BypassBulletproofTires",
    },
    ["Blacklist"] = {
        "BypassModelChanger",
        "BypassWeaponBlacklist"
    },
    ["Misc"] = {
        "FGCommands",
        "BypassVPN",
        "BypassExplosion",
        "BypassClearTasks",
        "BypassParticle",
    },
},
    ["mod"] = {
        ["Client"] = {
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
        ["Misc"] = {
            "FGCommands",
            "BypassVPN",
            "BypassExplosion",
            "BypassClearTasks",
            "BypassParticle",
        },
    },
    ["support"] = {
        ["Client"] = {
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
    },
    ["trialsupport"] = {
        ["Client"] = {
            "BypassSpectate",
            "BypassGodMode",
            "BypassInvisible",
            "BypassStealOutfit",
            "BypassInfStamina",
            "BypassNoclip",
            "BypassSuperJump",
            "BypassFreecam",
            "BypassSpeedHack",
            "BypassTeleport",
            "BypassNightVision",
            "BypassThermalVision",
            "BypassOCR",
            "BypassNuiDevtools",
            "BypassBlacklistedTextures",
            "BlipsBypass",
            "BypassCbScanner",
        },
    },
}